language: node_js

node_js:
  - v6

brances:
  only:
    - master

before_install:
  - npm install -g gulp yo generator-electrode-component
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'electrode-archetype-react-component' ]; then cd .. && eval "mv $currentfolder electrode-archetype-react-component" && cd electrode-archetype-react-component; fi
  - npm install
  - cd dev ; npm install ; cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # run the archetype check task.
  - gulp archetype:check

  # create a new component using electrode-component yeoman generator to run the components unit-tests.
  - yo electrode-component --projectName=product-card --packageName=product-card --packageGitHubOrg=walmartlabs --developerName="Arpan Nanavati" --ghUser=ananavati --ghRepo=product-card --createDirectory=Y
  - cd product-card

  # run ci tests and generate a bundle.
  - gulp check-ci
  - gulp build
