language: node_js
node_js:
  - v8
dist: trusty # needs Ubuntu Trusty
sudo: required  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
notifications:
  email:
    - XChen@walmartlabs.com
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; npm --version; fi
  - npm install -g xclap-cli fyn
